article/urls.py
from django.urls import path
from .views import (
    home,
    teams_article,
    accept,
    reject,
    request,
    article,
    register_newsletter,
    Create_Article,
    Update_Article,
    Delete_Article,
    )


app_name="article"
urlpatterns=[
    path("",home,name="home"),
    path("page/<int:page>/",home,name="home"),
    path("article/<int:article_id>/",article,name="article"),
    path("newsletter/register/",register_newsletter,name="newsletter"),
    path("teams/",teams_article,name="teams"),
    path("teams/page/<int:page>/",teams_article,name="teams"),
    path("article/<int:article_id>/accept/<username>/",accept,name="accept"),
    path("article/<int:article_id>/reject/<username>/",reject,name="reject"),
    path("article/<int:article_id>/request/",request,name="request"),
    path("article/create/",Create_Article.as_view(),name="create"),
    path("article/edit/<int:pk>/",Update_Article.as_view(),name="edit"),
    path("article/delete/<int:pk>/",Delete_Article.as_view(),name="delete"),
]

squadfinder/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path("account/",include("user.urls")),
    path("",include("article.urls")),
]

user/urls.py
from django.urls import path
from article.views import user_articles
from .views import (
setting,
account_profile,
Signup,
Login,
logout_view,
passwordreset,
passwordresetdone,
passwordresetcomplete,
passwordresetconfrim,
home,
)

app_name="user"
urlpatterns=[
    path("",home,name="home"),
    path("signup/",Signup,name="signup"),
    path("login/",Login.as_view(),name="login"),
    path("logout/",logout_view,name="logout"),
    path("profile/<str:username>/",account_profile,name="account_profile"),
    path("setting/",setting,name="user_setting"),
    path("reset_password/",passwordreset.as_view(),name="reset_password"),
    path("reset/<uidb64>/<token>/",passwordresetconfrim.as_view(),name="reset_password_confrim"),
    path("reset/done/",passwordresetcomplete.as_view(),name="reset_password_complete"),
    path("reset_password/done/",passwordresetdone.as_view(),name="reset_password_done"),
    path("articles/",user_articles,name="articles"),
    path("articles/page/<int:page>/",user_articles,name="articles"),
]

article/models.py
from django.db import models
from multiselectfield import MultiSelectField
from user.models import User,ROLE_CHOICES,SERVER_CHOICES,Rank
from django.utils import timezone
from user.models import validate_min
# Create your models here.
class Squad_Article(models.Model):
    class Meta:
        verbose_name="پست اسکواد"
        verbose_name_plural="پست اسکواد ها"
    author=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,verbose_name="نویسنده",related_name="article")
    role=MultiSelectField(max_length=11,max_choices=4,choices=ROLE_CHOICES,verbose_name="نقش")
    server=models.CharField(max_length=2,choices=SERVER_CHOICES,verbose_name="سرور")
    min_rank=models.ForeignKey(Rank,on_delete=models.CASCADE,related_name="squad_article",verbose_name="حداقل رنک")
    min_kd=models.FloatField(max_length=5,validators=[validate_min],verbose_name="حداقل kd")
    min_level=models.IntegerField(verbose_name="حداقل level",validators=[validate_min],)
    min_time_to_play=models.IntegerField(verbose_name="حداقل تایم بازی در روز(ساعت)",validators=[validate_min],)
    apply=models.ManyToManyField(User,blank=True,related_name="requested",verbose_name="متقاضیان")
    accepted=models.ManyToManyField(User,blank=True,related_name="accepted",verbose_name="متقاضیان قبول شده")
    rejected=models.ManyToManyField(User,blank=True,related_name="rejected",verbose_name="متقاضیان رد شده")
    publish=models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def new_apply(self):
        count_new_apply=self.apply.count() - (self.accepted.count() + self.rejected.count())
        if count_new_apply<0:
            count_new_apply=0
        return count_new_apply


class Newsletter(models.Model):
    class Meta:
        verbose_name="خبرنامه"
        verbose_name_plural="خبرنامه ها"
    email=models.EmailField(unique=True,null=False,verbose_name="ایمیل")
    join=models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.email

article/forms.py
from django.forms import ModelForm
from article.models import Squad_Article,Newsletter
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext as _
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent





class searchbar(ModelForm):
    def __init__(self, *args,**kwargs):

        super(searchbar,self).__init__(*args,**kwargs)
        # self.fields["server"].widget.option_template_name=BASE_DIR / "templates/article/forms/select_option.html"
        # self.fields["server"].widget.template_name=BASE_DIR / "templates/article/forms/select.html"
        self.fields["role"].required=False
        self.fields["server"].required=False
        self.fields["min_rank"].required=False
        self.fields["min_kd"].required=False
        # self.fields["role"].widget.template_name="article/forms/checkbox_select.html"
        # self.fields["role"].widget.option_template_name="article/forms/checkbox_option.html"
    class Meta:
        model=Squad_Article
        fields=["server","min_rank","min_kd","role"]


class newsletterform(ModelForm):
    def __init__(self, *args,**kwargs):

        super(newsletterform,self).__init__(*args,**kwargs)
        self.fields["email"].error_messages["unique"]=_("این ایمیل در خبرنامه موجود است",)
    
    class Meta:
        model=Newsletter
        fields=["email"]

article/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse,reverse_lazy
from django.core.paginator import Paginator
from .models import Squad_Article,Newsletter
import operator
from user.models import User,account_detail
from django.contrib.auth.decorators import login_required
from functools import reduce
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import (
    AUTHORACCESSMIXIN,
    FORMVALIDATEMIXIN,
    ARTICLEFIELDSMIXIN,
    ACCOUNTDETAILMIXIN,
    )
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import newsletterform, searchbar
from django.views.decorators.http import require_POST
# Create your views here.


_article_per_page=5


def home(request,page=1):
    articles=Squad_Article.objects.all().order_by("-publish")
    paginate=Paginator(articles,_article_per_page)
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"articles":article_page,"page_range":page_range}
    return render(request,"article/home.html",context=context)


def article(request,article_id):
    article=get_object_or_404(Squad_Article,pk=article_id)

    context={"article":article}
    return render(request,"article/article.html",context)


class Create_Article(LoginRequiredMixin,ACCOUNTDETAILMIXIN,ARTICLEFIELDSMIXIN,FORMVALIDATEMIXIN,CreateView):
    model=Squad_Article
    template_name="article/article_create_update.html"
    success_url=reverse_lazy("article:home")



class Update_Article(LoginRequiredMixin,AUTHORACCESSMIXIN,ARTICLEFIELDSMIXIN,FORMVALIDATEMIXIN,UpdateView):
    model=Squad_Article
    template_name="article/article_create_update.html"
    def get_success_url(self):
          article_id=self.kwargs['pk']
          return reverse_lazy('article:article', kwargs={'article_id': article_id})


class Delete_Article(LoginRequiredMixin,AUTHORACCESSMIXIN,DeleteView):
    model=Squad_Article
    success_url=reverse_lazy("article:home")
    template_name="article/article_delete.html"


def teams_article(request,page=1):
    form=searchbar(request.POST)
    if request.method=="POST":
        if form.is_valid():
            server=form.cleaned_data["server"]
            role=form.cleaned_data["role"]
            min_kd=form.cleaned_data["min_kd"]
            min_rank=form["min_rank"].value()
            return redirect(reverse("article:teams")+ f"?server={server}&role={role}&min_kd={min_kd}&min_rank={min_rank}")
    server=request.GET.get("server")
    role=request.GET.get("role")
    min_kd=request.GET.get("min_kd")
    min_rank=request.GET.get("min_rank")
    if server or role or min_kd or min_rank:
        role=role.replace(" ","")
        role=role.replace("'","")
        role=role[1:-1]
        role=role.split(",")
        if not min_kd.replace('.','',1).isdigit():
            min_kd=0
        if not min_rank.isdigit():
            min_rank=0
        if role==[""] or len(role)>4:
            articles=Squad_Article.objects.filter(
            Q(server__contains=server) & 
            Q(min_kd__gte=min_kd) &
            Q(min_rank__gte=min_rank)
            ).order_by("-publish")
        else:
            articles=Squad_Article.objects.filter(
                Q(server__contains=server) & 
                Q(min_kd__gte=min_kd) &
                Q(min_rank__gte=min_rank)
                ).filter(reduce(operator.and_, (Q(role__contains=x) for x in role))).order_by("-publish")

    else:

        articles=Squad_Article.objects.all().order_by("-publish")
        form=searchbar()
    paginate=Paginator(articles,_article_per_page)
    query=request.get_full_path()
    if "?" in query:
        query=query.split("?")[1]
    else:
        query=""
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"form":form,"articles":article_page,"page_range":page_range,"query":query}
    return render(request,"article/teams.html",context)
@login_required
def accept(request,article_id,username):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=get_object_or_404(User,username=username)
    if article.author==request.user or request.user==request.user.is_superuser:
        if user in article.apply.all():
            if user not in article.rejected.all():
                article.accepted.add(user)
                messages.success(request,f"شما یوزر {user.username} را قبول کردید")
    return redirect("article:article",article_id=article_id)
@login_required
def reject(request,article_id,username):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=get_object_or_404(User,username=username)
    if article.author==request.user or request.user==request.user.is_superuser and article.author != user:
        if user in article.apply.all():
            if user not in article.accepted.all():
                article.rejected.add(user)
                messages.warning(request,f"شما یوزر {user.username} را رد کردید")
    return redirect("article:article",article_id=article_id)

@login_required
def request(request,article_id):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=request.user
    acc_detail=account_detail.objects.filter(player=user).first()
    if acc_detail:
        if  user == user.is_superuser or article.author != user:
            if user not in article.apply.all():
                article.apply.add(user)
                messages.success(request,"شما درخواست خود را فرستادید")
    else:
        messages.error(request,"لطفا ابتدا اطلاعات اکانت خود را تکمیل کنید")
        return redirect("user:user_setting")
    return redirect("article:article",article_id=article_id)

@require_POST
def register_newsletter(request):
    form=newsletterform(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,"ایمیل شما با موفقیت ثبت شد")

    else:
        error_msg=form["email"].errors.as_text()

        messages.error(request,error_msg)
    return redirect(reverse("article:home"))


@login_required
def user_articles(request,page=1):
    user=request.user
    articles=Squad_Article.objects.filter(author=user)
    paginate=Paginator(articles,_article_per_page)
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"articles":article_page,"page_range":page_range}
    return render(request,"article/user_article.html",context=context)

templates/article/partials/articles.html
{% load humanize %}
{% load static %}
<section class="cards d-flex flex-column align-items-center mt-2">
        {% for article in articles %}
            <section class="custom-card rounded">
                <div>
                    <div class="card-header card-header-custom d-flex flex-column flex-sm-row align-items-center justify-content-between row border-bottom border-secondary">
                        <div class="card-header-right d-flex align-items-center">
                            <img class="rounded card-photo" src="{% static 'article/assets/images/pngaaa.com-512997.png' %} " alt="">
                            <h5 class="m-0"><a class="text-dark" href="{% url 'article:article' article.id %}">درخواست تیم</a></h5>
                        </div>
                        <div class="card-header-left flex-column flex-lg-row">
                            <span class="text-black-50 h6">{{article.publish|naturaltime}}</span>
                            <a href="{% url 'user:account_profile' article.author.username %}" class="text-success">توسط {% if article.author.first_name %}{{article.author.first_name}}{% else %}{{article.author.username}}{% endif %}</a>
                        </div>
                    </div>
                    <div class="card-custom-body">
                        <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                            <span class="">حداقل رنک:{{article.min_rank}}</span>
                            <span class="">سرور:{{article.get_server_display}}</span>
                        </div>
                        <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                            <span class="">نقش:{{article.role}}</span>
                            <span class="">حداقل کی دی:{{article.min_kd}}</span>
                        </div>
                        <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                            <span class="">حداقل لول:{{article.min_level}}</span>
                            <span class="">حداقل ساعت بازی:{{article.min_time_to_play}}</span>
                        </div>

                    </div>
                    <div class="card-custom-footer row justify-content-center justify-content-lg-end">
                        {% if request.user.is_authenticated %}
                            {% if request.user == article.author or request.user.is_superuser %}
                                <a href="{% url 'article:edit' article.id %}" class="btn btn-primary ml-2">ادیت</a>
                                <a href="{% url 'article:article' article.id %}" class="btn {% if article.new_apply > 0 %}btn-success {% else %}btn-info disabled{% endif %}">درخواست های جدید:{{article.new_apply}}</a>
                            {% else %}
                                {% if article not in request.user.requested.all %}
                                    <a href="{% url 'article:request' article.id %}" class="btn btn-primary">ارسال درخواست</a>
                                {% else %}
                                    {% if article in request.user.accepted.all %}
                                        <a href="#" class="btn btn-success disabled">درخواست شما قبول شده</a>
                                    {% elif article in request.user.rejected.all %}
                                        <a href="#" class="btn btn-danger disabled">درخواست شما رد شده</a>
                                    {% else %}
                                        <a href="#" class="btn btn-info disabled">درخواست فرستاده شده</a>

                                    {% endif %}

                                {% endif %}
                            {% endif %}
                            
                        {% else %}
                            <a href="{% url 'user:login' %}" class="btn btn-info">وارد شوید</a>
                        {% endif %}
                    </div>
                </div>
            </section>
        {% empty %}
            <section class="empty-warn bg-warning p-4 text-center rounded">
                <span>هیچ مقاله ای موجود نیست.</span>
            </section>
        {% endfor %}
    </section>

templates/article/partials/newsletterform.html
{% load widget_tweaks %}

<form class="form-newsletter d-lg-block d-flex flex-column align-items-center" method="POST" action="{% url 'article:newsletter' %}">
    {% csrf_token %}
    <i class="fas fa-envelope d-none d-lg-inline"></i>
    {{form.email|attr:"placeholder:email"}}
    <button type="submit" class="btn btn-success">عضویت</button>
</form>

templates/article/partials/pagination.html
<section class="pagination-container mt-3">
    <div class="text-center mx-3 mx-sm-0">
        <div class="pagination-custom">
        {% if pages.has_previous %}
            <a href="{% url link pages.previous_page_number %}">&raquo;</a>
        {% endif %}
        {% for page in page_range %}
            {% if page == pages.number %}
                <a class="active-custom" href="{% url link page %}">{{page}}</a>
            
            {% else %}
                {% if page == pages.paginator.ELLIPSIS %}
                    <a class="active-custom" href="#">{{page}}</a>
                {% else %}
                    <a href="{% url link page %}">{{page}}</a>
                {% endif %}
            
            {% endif %}
        {% endfor %}
        {% if pages.has_next %}
            <a href="{% url link pages.next_page_number %}">&laquo;</a>
        {% endif %}
        </div>
    </div>
</section>