squadfinder/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path("account/",include("user.urls")),
    path("",include("article.urls")),
]

user/urls.py
from django.urls import path
from article.views import user_articles
from .views import (
setting,
account_profile,
Signup,
Login,
logout_view,
passwordreset,
passwordresetdone,
passwordresetcomplete,
passwordresetconfrim,
home,
)

app_name="user"
urlpatterns=[
    path("",home,name="home"),
    path("signup/",Signup,name="signup"),
    path("login/",Login.as_view(),name="login"),
    path("logout/",logout_view,name="logout"),
    path("profile/<str:username>/",account_profile,name="account_profile"),
    path("setting/",setting,name="user_setting"),
    path("reset_password/",passwordreset.as_view(),name="reset_password"),
    path("reset/<uidb64>/<token>/",passwordresetconfrim.as_view(),name="reset_password_confrim"),
    path("reset/done/",passwordresetcomplete.as_view(),name="reset_password_complete"),
    path("reset_password/done/",passwordresetdone.as_view(),name="reset_password_done"),
    path("articles/",user_articles,name="articles"),
    path("articles/page/<int:page>/",user_articles,name="articles"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from multiselectfield import MultiSelectField
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.utils import timezone
# Create your models here.





def validate_min(value):
    if value < 1:
        raise ValidationError(
            _(f'عدد باید بزرگ تر از 0 باشد'),
        )

ROLE_CHOICES = [
    ('sn', 'sniper'),
    ('ca', 'camper'),
    ('ru', 'rusher'),
    ('co', 'cover'),
    ]

SERVER_CHOICES = [
        ("EU","europe"),
        ("AS","asia"),
        ("KO","korea"),
        ("AF","africa"),
        ("US","america"),
]




class User(AbstractUser):
    email=models.EmailField(unique=True,null=False,verbose_name="ایمیل")
    phonenumber=models.CharField(max_length=13,unique=True,null=True,blank=True,default=None,verbose_name="شماره موبایل")
    phone_verify=models.BooleanField(default=False,verbose_name="وریفای ایمیل")
    email_verify=models.BooleanField(default=False,verbose_name="وریفای شماره")
    phone_sms=models.BooleanField(default=False,verbose_name="دریافت sms")
    email_notif=models.BooleanField(default=False,verbose_name="دریافت ایمیل")
    REQUIRED_FIELDS = ['email']
    def __str__(self) -> str:
        return f"{self.username}"

class Rank(models.Model):
    class Meta:
        verbose_name="رنک"
        verbose_name_plural="رنک ها"
        ordering=["position"]
    title=models.CharField(max_length=30,verbose_name="اسم رنک")
    position=models.IntegerField(unique=True)

    def __str__(self) -> str:
        return self.title

class account_detail(models.Model):

    class Meta:
        verbose_name="اطلاعات اکانت"
        verbose_name_plural="اطلاعات اکانت ها"
    player=models.OneToOneField(User,related_name="acc_detail",null=True,default=None,on_delete=models.CASCADE)


    rank=models.ForeignKey(Rank,on_delete=models.CASCADE,related_name="acc_detail")
    start_season=models.IntegerField(validators=[validate_min],verbose_name="سیزن شروع بازی")
    role=MultiSelectField(max_length=11,max_choices=4,choices=ROLE_CHOICES,verbose_name="نقش")
    server=models.CharField(max_length=2,choices=SERVER_CHOICES,verbose_name="سرور")
    level=models.IntegerField(default=None,validators=[validate_min],verbose_name="لول شما")
    id_game=models.CharField(max_length=20,default=None,verbose_name="ایدی شما در بازی")
    username_game=models.CharField(default=None,max_length=60,verbose_name="یوزرنیم شما در بازی")
    kd=models.FloatField(max_length=5,default=None,verbose_name="kd شما")
    time_to_play=models.IntegerField(verbose_name="میزان ساعت بازی در روز",validators=[validate_min])
    def __str__(self) -> str:
        return f"{self.start_season}"

    def get_player_username(self):
        if self.player:
            return self.player.username
        else:
            return "-"
    get_player_username.short_description="player"

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from .models import User, account_detail
from django.forms import ModelForm, fields, models, widgets
from crispy_forms.helper import FormHelper
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordResetForm
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class signupfrom(UserCreationForm):

    def __init__(self, *args, **kwargs):

        super(signupfrom, self).__init__(*args, **kwargs)
        self.fields["captcha"] = ReCaptchaField(widget=ReCaptchaV2Checkbox)
        self.fields["username"].help_text = None
        self.fields["first_name"].help_text = "اختیاری"
        self.fields["last_name"].help_text = "اختیاری"
        self.fields["password1"].label = "پسورد"
        self.fields["password1"].help_text = None
        self.fields["password2"].label = "تایید پسورد"
        self.fields["password2"].help_text = None

    class Meta:
        model = User
        fields = ("username", "email", "first_name",
                  "last_name", "password1", "password2")

    UserCreationForm.error_messages["username_exist"] = _(
        "این نام کاربری در سایت موجود است.",)
    UserCreationForm.error_messages["email_exist"] = _(
        "این ایمیل در سایت موجود است.",)

    def clean_username(self):
        username = self.cleaned_data.get("username")
        user = User.objects.filter(username=username).first()
        if user:
            raise ValidationError(
                self.error_messages['username_exist'],
                code='username_exist',
            )
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user = User.objects.filter(email=email).first()
        if user:
            raise ValidationError(
                self.error_messages['email_exist'],
                code='email_exist',
            )
        return email


class loginform(AuthenticationForm):

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    AuthenticationForm.error_messages['invalid_login'] = _(
        "یوزرنیم یا پسورد اشتباه است، دوباره امتحان کنید.",)


class acc_detail_form(ModelForm):
    def __init__(self, *args, **kwargs):

        super(acc_detail_form, self).__init__(*args, **kwargs)
        self.fields["role"].label = "نقش"
        self.fields["start_season"].label = "فصل شروع بازی"

    class Meta:
        model = account_detail
        fields = ["rank", "start_season", "role", "server", "level",
                  "id_game", "username_game", "kd", "time_to_play", ]


class user_detail_form(ModelForm):
    def __init__(self, *args, **kwargs):
        super(user_detail_form, self).__init__(*args, **kwargs)
        self.fields["username"].disabled = True
        self.fields["username"].help_text = None
        self.fields["email"].disabled = True
        self.fields["phone_verify"].disabled = True
        self.fields["email_verify"].disabled = True
        self.fields['username'].label = False
        self.fields["email"].label = False
        # self.helper=FormHelper()
        # self.helper.form_show_labels = True
        # for field in user_detail_form.Meta.unlabelled_fields:
        #     self.fields[field].label = False

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email",
                  "phonenumber", "phone_verify", "email_verify", ]


class change_password(PasswordChangeForm):
    pass


class notifform(ModelForm):

    class Meta:
        model = User
        fields = ["email_notif", "phone_sms"]


class emailvalidatepasswordreset(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email=email).first():
            msg = _("ایمیل شما در سایت موجود نمیباشد")
            self.add_error('email', msg)
        return email

user/views.py
from django.contrib import auth
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from .models import User,account_detail
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, request
from .forms import signupfrom,loginform,acc_detail_form,user_detail_form,change_password,emailvalidatepasswordreset,notifform
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import CHECKUSERMIXIN
from .decorators import checkuser
from django.views.generic.edit import UpdateView
from django.views.decorators.http import require_POST
# Create your views here.

@checkuser
def Signup(request):
    if request.method=="POST":
        form=signupfrom(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.save()
            messages.success(request,"اکانت شما ساخته شد")
            return redirect("user:login")

    else:
        
        form=signupfrom()
    return render(request,"user/auth/signup.html",context={"form":form})




class Login(CHECKUSERMIXIN,LoginView):
    template_name="user/auth/login.html"
    authentication_form=loginform



@login_required
def home(request):
    return render(request,"user/account/home.html")



def logout_view(request):
    logout(request)
    messages.success(request,"شما از اکانت خود خارج شدید.")
    return redirect("user:login")


def home(request):
    return redirect("user:user_setting")



def account_profile(request,username):
    user=get_object_or_404(User,username=username)
    context={"pk_user":user}
    return render(request,"user/account/profile.html",context=context)

@login_required
def setting(request):
    if request.method=="POST":
        acc_detail=account_detail.objects.filter(player=request.user).first()
        if  "update_profile" in  request.POST:
            form_user_detail=user_detail_form(request.POST,instance=request.user)
            if form_user_detail.is_valid():
                form_user_detail.save()
            if acc_detail:
                form_account_detail=acc_detail_form(instance=acc_detail)
            else:
                form_account_detail=acc_detail_form()
            form_change_pass=change_password(request.user)
            form_notif=notifform(instance=request.user)
        elif "update_account" in request.POST:
            if acc_detail:
                form_account_detail=acc_detail_form(request.POST,instance=acc_detail)
                if form_account_detail.is_valid():
                    acc_detail=form_account_detail.save(commit=False)
                    acc_detail.player=request.user
                    acc_detail.save()


            else:
                form_account_detail=acc_detail_form(request.POST)
                if form_account_detail.is_valid():
                    acc_detail=form_account_detail.save(commit=False)
                    acc_detail.player=request.user
                    acc_detail.save()
            form_user_detail=user_detail_form(instance=request.user)
            form_change_pass=change_password(request.user)
            form_notif=notifform(instance=request.user)
        elif "update_password" in request.POST:
            form_change_pass=change_password(request.user,request.POST)
            if form_change_pass.is_valid():
                form_change_pass.save()
                messages.success(request,"پسورد شما با موفقیت تغییر کرد")
            if acc_detail:
                form_account_detail=acc_detail_form(instance=acc_detail)
            else:
                form_account_detail=acc_detail_form()
            form_user_detail=user_detail_form(instance=request.user)
            form_notif=notifform(instance=request.user)
        elif "update_notif" in request.POST:
            form_notif=notifform(request.POST,instance=request.user)
            if form_notif.is_valid():
                form_notif.save()
                messages.success(request,"تنظیمات اطلاعیه ها بروزرسانی شد")
            form_user_detail=user_detail_form(instance=request.user)
            if acc_detail:
                form_account_detail=acc_detail_form(instance=acc_detail)
            else:
                form_account_detail=acc_detail_form()
            form_change_pass=change_password(request.user)
            
            
    else:
        acc_detail=account_detail.objects.filter(player=request.user).first()
        if acc_detail:
            form_account_detail=acc_detail_form(instance=acc_detail)
        else:
            form_account_detail=acc_detail_form()
        form_user_detail=user_detail_form(instance=request.user)
        form_change_pass=change_password(request.user)
        form_notif=notifform(instance=request.user)

    context={"form_user":form_user_detail,"form_account":form_account_detail,
    "form_change_pass":form_change_pass,"form_notif":form_notif}
    return render(request,"user/account/setting.html",context)


class passwordreset(PasswordResetView):

    template_name="user/account/password_reset_form.html"
    success_url=reverse_lazy("user:reset_password_done")
    email_template_name='user/account/password_reset_email.html'
    form_class=emailvalidatepasswordreset

class passwordresetdone(PasswordResetDoneView):
    template_name="user/account/password_reset_done.html"

class passwordresetconfrim(PasswordResetConfirmView):
    template_name="user/account/password_reset_confrim.html"
    success_url=reverse_lazy("user:reset_password_complete")


class passwordresetcomplete(PasswordResetCompleteView):
    template_name="user/account/password_reset_complete.html"

templates/user/account/password_reset_complete.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}

{% block title %}پسورد ریست{% endblock title %}


{% block content %}
<section class="cards d-flex flex-column align-items-center mt-2">
    <section class="custom-card rounded">
        <div>
            <div class="d-flex flex-column flex-sm-row align-items-center justify-content-between row">
                <div class="card-header-right d-flex align-items-center">
                    <h5 class="m-0">عوض کردن پسورد</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">
                </div>
            </div>
            <hr>
            <div class="card-custom-body">
                    <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                        <p class="h5 text-success">پسورد شما با موفقیت تغییر کرد</p>
                    </div>
                
            </div>

        </div>
    </section>
</section>
{% endblock content %}

templates/user/account/password_reset_confrim.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}


{% block title %}پسورد ریست{% endblock title %}

{% block content %}
<section class="cards d-flex flex-column align-items-center mt-2">
    <section class="custom-card rounded">
        <div>
            <div class="d-flex flex-column flex-sm-row align-items-center justify-content-between row">
                <div class="card-header-right d-flex align-items-center">
                    <h5 class="m-0">عوض کردن پسورد</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">
                </div>
            </div>
            <hr>
            <div class="card-custom-body">
                {% if validlink %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.new_password1|as_crispy_field}}
                        </div>
                        <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.new_password2|as_crispy_field}}
                        </div>
                        <hr>
                        <button class="btn btn-success" type="submit">عوض کردن پسورد</button>
                    </form>
                {% else %}
                    <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                        <p class="h5 text-danger">لینک شما منقضی شده است</p>
                    </div>
                {% endif %}
            </div>

        </div>
    </section>
</section>
{% endblock content %}

templates/user/account/password_reset_done.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}


{% block title %}پسورد ریست{% endblock title %}

{% block content %}
<section class="cards d-flex flex-column align-items-center mt-2">
    <section class="custom-card rounded">
        <div>
            <div class="d-flex flex-column flex-sm-row align-items-center justify-content-between row">
                <div class="card-header-right d-flex align-items-center">
                    <h5 class="m-0">فراموشی پسورد</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">
                </div>
            </div>
            <hr>
            <div class="card-custom-body">
                <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                    <p>ایمیل بازیابی پسورد برای شما فرستاده شد.</p>
                </div>
            </div>

        </div>
    </section>
</section>
{% endblock content %}

templates/user/account/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'user:reset_password_confrim' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/user/account/password_reset_form.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}


{% block title %}پسورد ریست{% endblock title %}

{% block content %}
<section class="cards d-flex flex-column align-items-center mt-2">
    <section class="custom-card rounded">
        <div>
            <div class="d-flex flex-column flex-sm-row align-items-center justify-content-between row">
                <div class="card-header-right d-flex align-items-center">
                    <h5 class="m-0">فراموشی پسورد</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">
                </div>
            </div>
            <hr>
            <form method="POST">
                {% csrf_token %}
                <div class="card-custom-body">
                    <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                        {{form.email|as_crispy_field}}
                    </div>
                </div>
                <hr>
                <div class="card-custom-footer row justify-content-center justify-content-lg-end">
                    <button type="submit" class="btn btn-success">ارسال ایمیل</button>
                </div>
            </form>
        </div>
    </section>
</section>
{% endblock content %}

templates/user/account/profile.html
{% load gravatar %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title>اسکواد فایندر-پروفایل:{{pk_user.username}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'article/assets/js/jquery-3.5.1.min.js' %}"></script>
    <link href="{% static 'article/assets/css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'article/assets/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</head>
<body >
<section class="section about-section gray-bg" id="about">
            
                <div class="container">
                    <div class="row align-items-center flex-row-reverse">
                        <div dir="rtl" class="col-lg-6 text-right">
                            <div class="about-text go-to">
                                <h3 class="dark-color">{{pk_user.username}}</h3>
                                <h6 class="theme-color lead">{{pk_user.get_full_name}}</h6>
                                {% if pk_user.acc_detail %}
                                    <div class="row about-list">
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label>تعداد درخواست اسکواد</label>
                                                <p>{{pk_user.article.count}}</p>
                                            </div>
                                            <div class="media">
                                                <label>نقش</label>
                                                <p>{{pk_user.acc_detail.role}}</p>
                                            </div>
                                            <div class="media">
                                                <label>سیزن شروع بازی</label>
                                                <p>{{pk_user.acc_detail.start_season}}</p>
                                            </div>

                                        </div>
                                        <div class="col-md-6">
                                            <div class="media">
                                                <label>تایم بازی</label>
                                                <p>{{pk_user.acc_detail.time_to_play}}ساعت</p>
                                            </div>

                                        </div>
                                    </div>
                                {% else %}
                                    <div class="container text-center">
                                        <h7 class="theme-color lead">کاربر اطلاعات خود را وارد نکرده است</h7>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="about-avatar">
                                <img src="{% gravatar_url pk_user.email 300 %}" title="" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="counter">
                        <div class="row">
                            <div class="col-6 col-lg-3">
                                <div class="count-data text-center">
                                    <h6 class="count h2" data-to="500" data-speed="500">{{pk_user.acc_detail.kd}}</h6>
                                    <p class="m-0px font-w-600">kd</p>
                                </div>
                            </div>
                            <div class="col-6 col-lg-3">
                                <div class="count-data text-center">
                                    <h6 class="count h2" data-to="150" data-speed="150">{{pk_user.acc_detail.rank}}</h6>
                                    <p class="m-0px font-w-600">rank</p>
                                </div>
                            </div>
                            <div class="col-6 col-lg-3">
                                <div class="count-data text-center">
                                    <h6 class="count h2" data-to="850" data-speed="850">{{pk_user.acc_detail.level}}</h6>
                                    <p class="m-0px font-w-600">level</p>
                                </div>
                            </div>
                            <div class="col-6 col-lg-3">
                                <div class="count-data text-center">
                                    <h6 class="count h2" data-to="190" data-speed="190">{{pk_user.acc_detail.get_server_display}}</h6>
                                    <p class="m-0px font-w-600">server</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        </section>

<style type="text/css">
@font-face {
    font-family: sahel;
    src: url(../../../static/user/auth/fonts/Sahel.ttf);
}
body{
    background-image: url(../../../static/user/auth/images/pubg2.jpg);
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    font-family: sahel;
    color: #6F8BA4;
    margin-top:20px;
}
.section {
    padding: 100px 0;
    position: relative;
    opacity: 0.9;
}
.gray-bg {
    background-color: #f5f5f5;
}
img {
    max-width: 100%;
}
img {
    vertical-align: middle;
    border-style: none;
}
/* About Me 
---------------------*/
.about-text h3 {
  font-size: 45px;
  font-weight: 700;
  margin: 0 0 6px;
}
@media (max-width: 767px) {
  .about-text h3 {
    font-size: 35px;
  }
}
.about-text h6 {
  font-weight: 600;
  margin-bottom: 15px;
}
@media (max-width: 767px) {
  .about-text h6 {
    font-size: 18px;
  }
}
.about-text p {
  font-size: 18px;
  max-width: 450px;
}
.about-text p mark {
  font-weight: 600;
  color: #20247b;
}

.about-list {
  padding-top: 10px;
}
.about-list .media {
  padding: 5px 0;
}
.about-list label {
  color: #20247b;
  font-weight: 600;
  width: 120px;
  margin: 0;
  position: relative;
}
/* .about-list label:after {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  right: 11px;
  width: 1px;
  height: 12px;
  background: #20247b;
  -moz-transform: rotate(15deg);
  -o-transform: rotate(15deg);
  -ms-transform: rotate(15deg);
  -webkit-transform: rotate(15deg);
  transform: rotate(15deg);
  margin: auto;
  opacity: 0.5;
} */
.about-list p {
  margin: 0;
  font-size: 15px;
}
.about-avatar img{
    border-radius: 5px;
}

@media (max-width: 991px) {
  .about-avatar {
    margin-top: 30px;
    text-align: center;
  }
}

.about-section .counter {
  padding: 22px 20px;
  background: #ffffff;
  border-radius: 10px;
  box-shadow: 0 0 30px rgba(31, 45, 61, 0.125);
}
.about-section .counter .count-data {
  margin-top: 10px;
  margin-bottom: 10px;
}
.about-section .counter .count {
  font-weight: 700;
  color: #20247b;
  margin: 0 0 5px;
}
.about-section .counter p {
  font-weight: 600;
  margin: 0;
}
mark {
    background-image: linear-gradient(rgba(252, 83, 86, 0.6), rgba(252, 83, 86, 0.6));
    background-size: 100% 3px;
    background-repeat: no-repeat;
    background-position: 0 bottom;
    background-color: transparent;
    padding: 0;
    color: currentColor;
}
.theme-color {
    color: #fc5356;
}
.dark-color {
    color: #20247b;
}


</style>

<script type="text/javascript">

</script>
</body>
</html>

templates/user/account/user_detail.html
{% extends "article/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="box box-info">
        <div class="box-header with-border">
        <h3 class="box-title">ویرایش اطلاعات شما</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="mt-3" method="POST" action="">
            {% csrf_token %}
            
            <div class="row">
                <div class="form-group col-md-6 mb-0">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        {{form.username|as_crispy_field}}
                    </div>
                </div>

                <div class="form-group col-md-6 mb-0">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        {{ form.email|as_crispy_field }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 mb-0">
                    {{form.first_name|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 mb-0">
                    {{form.phonenumber|as_crispy_field}}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.email_verify|as_crispy_field }}
                    {{ form.phone_verify|as_crispy_field }}
                </div>
            </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-info pull-right">ویرایش</button>
        </div>
        <!-- /.box-footer -->
        </form>
    </div>

    
{% endblock %}