article/urls.py
from django.urls import path
from .views import (
    home,
    teams_article,
    accept,
    reject,
    request,
    article,
    register_newsletter,
    Create_Article,
    Update_Article,
    Delete_Article,
    )


app_name="article"
urlpatterns=[
    path("",home,name="home"),
    path("page/<int:page>/",home,name="home"),
    path("article/<int:article_id>/",article,name="article"),
    path("newsletter/register/",register_newsletter,name="newsletter"),
    path("teams/",teams_article,name="teams"),
    path("teams/page/<int:page>/",teams_article,name="teams"),
    path("article/<int:article_id>/accept/<username>/",accept,name="accept"),
    path("article/<int:article_id>/reject/<username>/",reject,name="reject"),
    path("article/<int:article_id>/request/",request,name="request"),
    path("article/create/",Create_Article.as_view(),name="create"),
    path("article/edit/<int:pk>/",Update_Article.as_view(),name="edit"),
    path("article/delete/<int:pk>/",Delete_Article.as_view(),name="delete"),
]

squadfinder/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
urlpatterns = [
    path('admin/', admin.site.urls,name="admin"),
    path("account/",include("user.urls")),
    path("",include("article.urls")),
]

user/urls.py
from django.urls import path
from article.views import user_articles
from .views import (
setting,
account_profile,
Signup,
Login,
logout_view,
passwordreset,
passwordresetdone,
passwordresetcomplete,
passwordresetconfrim,
home,
)

app_name="user"
urlpatterns=[
    path("",home,name="home"),
    path("signup/",Signup,name="signup"),
    path("login/",Login.as_view(),name="login"),
    path("logout/",logout_view,name="logout"),
    path("profile/<str:username>/",account_profile,name="account_profile"),
    path("setting/",setting,name="user_setting"),
    path("reset_password/",passwordreset.as_view(),name="reset_password"),
    path("reset/<uidb64>/<token>/",passwordresetconfrim.as_view(),name="reset_password_confrim"),
    path("reset/done/",passwordresetcomplete.as_view(),name="reset_password_complete"),
    path("reset_password/done/",passwordresetdone.as_view(),name="reset_password_done"),
    path("articles/",user_articles,name="articles"),
    path("articles/page/<int:page>/",user_articles,name="articles"),
]

article/models.py
from django.db import models
from multiselectfield import MultiSelectField
from user.models import User,ROLE_CHOICES,SERVER_CHOICES,Rank
from django.utils import timezone
from user.models import validate_min
# Create your models here.
class Squad_Article(models.Model):
    class Meta:
        verbose_name="پست اسکواد"
        verbose_name_plural="پست اسکواد ها"
    author=models.ForeignKey(User,null=True,on_delete=models.SET_NULL,verbose_name="نویسنده",related_name="article")
    role=MultiSelectField(max_length=11,max_choices=4,choices=ROLE_CHOICES,verbose_name="نقش")
    server=models.CharField(max_length=2,choices=SERVER_CHOICES,verbose_name="سرور")
    min_rank=models.ForeignKey(Rank,on_delete=models.CASCADE,related_name="squad_article",verbose_name="حداقل رنک")
    min_kd=models.FloatField(max_length=5,validators=[validate_min],verbose_name="حداقل kd")
    min_level=models.IntegerField(verbose_name="حداقل level",validators=[validate_min],)
    min_time_to_play=models.IntegerField(verbose_name="حداقل تایم بازی در روز(ساعت)",validators=[validate_min],)
    apply=models.ManyToManyField(User,blank=True,related_name="requested",verbose_name="متقاضیان")
    accepted=models.ManyToManyField(User,blank=True,related_name="accepted",verbose_name="متقاضیان قبول شده")
    rejected=models.ManyToManyField(User,blank=True,related_name="rejected",verbose_name="متقاضیان رد شده")
    publish=models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def new_apply(self):
        count_new_apply=self.apply.count() - (self.accepted.count() + self.rejected.count())
        if count_new_apply<0:
            count_new_apply=0
        return count_new_apply


class Newsletter(models.Model):
    class Meta:
        verbose_name="خبرنامه"
        verbose_name_plural="خبرنامه ها"
    email=models.EmailField(unique=True,null=False,verbose_name="ایمیل")
    join=models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.email

article/forms.py
from django.forms import ModelForm
from article.models import Squad_Article,Newsletter
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext as _
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent





class searchbar(ModelForm):
    def __init__(self, *args,**kwargs):

        super(searchbar,self).__init__(*args,**kwargs)
        # self.fields["server"].widget.option_template_name=BASE_DIR / "templates/article/forms/select_option.html"
        # self.fields["server"].widget.template_name=BASE_DIR / "templates/article/forms/select.html"
        self.fields["role"].required=False
        self.fields["server"].required=False
        self.fields["min_rank"].required=False
        self.fields["min_kd"].required=False
        # self.fields["role"].widget.template_name="article/forms/checkbox_select.html"
        # self.fields["role"].widget.option_template_name="article/forms/checkbox_option.html"
    class Meta:
        model=Squad_Article
        fields=["server","min_rank","min_kd","role"]


class newsletterform(ModelForm):
    def __init__(self, *args,**kwargs):

        super(newsletterform,self).__init__(*args,**kwargs)
        self.fields["email"].error_messages["unique"]=_("این ایمیل در خبرنامه موجود است",)
    
    class Meta:
        model=Newsletter
        fields=["email"]

article/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse,reverse_lazy
from django.core.paginator import Paginator
from .models import Squad_Article,Newsletter
import operator
from user.models import User,account_detail
from django.contrib.auth.decorators import login_required
from functools import reduce
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import (
    AUTHORACCESSMIXIN,
    FORMVALIDATEMIXIN,
    ARTICLEFIELDSMIXIN,
    ACCOUNTDETAILMIXIN,
    )
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .forms import newsletterform, searchbar
from django.views.decorators.http import require_POST
# Create your views here.


_article_per_page=5


def home(request,page=1):
    articles=Squad_Article.objects.all().order_by("-publish")
    paginate=Paginator(articles,_article_per_page)
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"articles":article_page,"page_range":page_range}
    return render(request,"article/home.html",context=context)


def article(request,article_id):
    article=get_object_or_404(Squad_Article,pk=article_id)

    context={"article":article}
    return render(request,"article/article.html",context)


class Create_Article(LoginRequiredMixin,ACCOUNTDETAILMIXIN,ARTICLEFIELDSMIXIN,FORMVALIDATEMIXIN,CreateView):
    model=Squad_Article
    template_name="article/article_create_update.html"
    success_url=reverse_lazy("article:home")



class Update_Article(LoginRequiredMixin,AUTHORACCESSMIXIN,ARTICLEFIELDSMIXIN,FORMVALIDATEMIXIN,UpdateView):
    model=Squad_Article
    template_name="article/article_create_update.html"
    def get_success_url(self):
          article_id=self.kwargs['pk']
          return reverse_lazy('article:article', kwargs={'article_id': article_id})


class Delete_Article(LoginRequiredMixin,AUTHORACCESSMIXIN,DeleteView):
    model=Squad_Article
    success_url=reverse_lazy("article:home")
    template_name="article/article_delete.html"


def teams_article(request,page=1):
    form=searchbar(request.POST)
    if request.method=="POST":
        if form.is_valid():
            server=form.cleaned_data["server"]
            role=form.cleaned_data["role"]
            min_kd=form.cleaned_data["min_kd"]
            min_rank=form["min_rank"].value()
            return redirect(reverse("article:teams")+ f"?server={server}&role={role}&min_kd={min_kd}&min_rank={min_rank}")
    server=request.GET.get("server")
    role=request.GET.get("role")
    min_kd=request.GET.get("min_kd")
    min_rank=request.GET.get("min_rank")
    if server or role or min_kd or min_rank:
        role=role.replace(" ","")
        role=role.replace("'","")
        role=role[1:-1]
        role=role.split(",")
        if not min_kd.replace('.','',1).isdigit():
            min_kd=0
        if not min_rank.isdigit():
            min_rank=0
        if role==[""] or len(role)>4:
            articles=Squad_Article.objects.filter(
            Q(server__contains=server) & 
            Q(min_kd__gte=min_kd) &
            Q(min_rank__gte=min_rank)
            ).order_by("-publish")
        else:
            articles=Squad_Article.objects.filter(
                Q(server__contains=server) & 
                Q(min_kd__gte=min_kd) &
                Q(min_rank__gte=min_rank)
                ).filter(reduce(operator.and_, (Q(role__contains=x) for x in role))).order_by("-publish")

    else:

        articles=Squad_Article.objects.all().order_by("-publish")
        form=searchbar()
    paginate=Paginator(articles,_article_per_page)
    query=request.get_full_path()
    if "?" in query:
        query=query.split("?")[1]
    else:
        query=""
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"form":form,"articles":article_page,"page_range":page_range,"query":query}
    return render(request,"article/teams.html",context)
@login_required
def accept(request,article_id,username):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=get_object_or_404(User,username=username)
    if article.author==request.user or request.user==request.user.is_superuser:
        if user in article.apply.all():
            if user not in article.rejected.all():
                article.accepted.add(user)
                messages.success(request,f"شما یوزر {user.username} را قبول کردید")
    return redirect("article:article",article_id=article_id)
@login_required
def reject(request,article_id,username):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=get_object_or_404(User,username=username)
    if article.author==request.user or request.user==request.user.is_superuser and article.author != user:
        if user in article.apply.all():
            if user not in article.accepted.all():
                article.rejected.add(user)
                messages.warning(request,f"شما یوزر {user.username} را رد کردید")
    return redirect("article:article",article_id=article_id)

@login_required
def request(request,article_id):
    article=get_object_or_404(Squad_Article,pk=article_id)
    user=request.user
    acc_detail=account_detail.objects.filter(player=user).first()
    if acc_detail:
        if  user == user.is_superuser or article.author != user:
            if user not in article.apply.all():
                article.apply.add(user)
                messages.success(request,"شما درخواست خود را فرستادید")
    else:
        messages.error(request,"لطفا ابتدا اطلاعات اکانت خود را تکمیل کنید")
        return redirect("user:user_setting")
    return redirect("article:article",article_id=article_id)

@require_POST
def register_newsletter(request):
    form=newsletterform(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request,"ایمیل شما با موفقیت ثبت شد")

    else:
        error_msg=form["email"].errors.as_text()

        messages.error(request,error_msg)
    return redirect(reverse("article:home"))


@login_required
def user_articles(request,page=1):
    user=request.user
    articles=Squad_Article.objects.filter(author=user)
    paginate=Paginator(articles,_article_per_page)
    article_page=paginate.get_page(page)
    page_range=paginate.get_elided_page_range(page, on_each_side=1, on_ends=2)
    page_range=list(page_range)
    context={"articles":article_page,"page_range":page_range}
    return render(request,"article/user_article.html",context=context)

templates/article/article.html
{% extends 'article/base.html' %}
{% load static %}
{% load humanize %}

{% block style_link %}
    <link rel="stylesheet" href="{% static 'article/assets/css/timeline.css' %}">
{% endblock style_link %}


{% block title %}{{article.id}}{% endblock title %}

{% block content %}
<section class="cards d-flex flex-column align-items-center mt-2">
    <section class="custom-card rounded">
        <div>
            <div class="card-header card-header-custom d-flex flex-column flex-sm-row align-items-center justify-content-between row border-bottom border-secondary">
                <div class="card-header-right d-flex align-items-center">
                    <img class="rounded card-photo" src="{% static 'article/assets/images/pngaaa.com-512997.png' %} " alt="">
                    <h5 class="m-0">درخواست تیم</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">
                    <span class="text-black-50 h6">{{article.publish|naturaltime}}</span>
                    <a href="{% url 'user:account_profile' article.author.username %}" class="text-success">توسط {% if article.author.first_name %}{{article.author.first_name}}{% else %}{{article.author.username}}{% endif %}</a>
                </div>
            </div>
            <div class="card-custom-body">
                <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                    <span class="">حداقل رنک:{{article.min_rank}}</span>
                    <span class="">سرور:{{article.get_server_display}}</span>
                </div>
                <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                    <span class="">نقش:{{article.role}}</span>
                    <span class="">حداقل کی دی:{{article.min_kd}}</span>
                </div>
                <div class="row flex-column flex-lg-row justify-content-around align-items-center">
                    <span class="">حداقل لول:{{article.min_level}}</span>
                    <span class="">حداقل ساعت بازی:{{article.min_time_to_play}}</span>
                </div>
                <div class="card-footer card-footer-custom">
                    <div class="row">
                        <span class="col-12 col-sm-4">تعداد درخواست:{{article.apply.count}}</span>
                        <span class="col-12 col-sm-4">تعداد قبولی:{{article.accepted.count}}</span>
                        <span class="col-12 col-sm-4">تعداد ردی:{{article.rejected.count}}</span>
                    </div>
                </div>
            </div>
            <div class="card-custom-footer row justify-content-center justify-content-lg-end">
                {% if request.user.is_authenticated %}
                    {% if request.user == article.author or request.user.is_superuser %}
                        <a href="{% url 'article:edit' article.id %}" class="btn btn-primary ml-2">ادیت</a>
                        <a href="#" class="btn disabled {% if article.new_apply > 0 %}btn-success {% else %}btn-info{% endif %}">درخواست های جدید:{{article.new_apply}}</a>
                    {% else %}
                        {% if article not in request.user.requested.all %}
                            <a href="{% url 'article:request' article.id %}" class="btn btn-primary">ارسال درخواست</a>
                        {% else %}
                            {% if article in request.user.accepted.all %}
                                <a href="#" class="btn btn-success disabled">درخواست شما قبول شده</a>
                            {% elif article in request.user.rejected.all %}
                                <a href="#" class="btn btn-danger disabled">درخواست شما رد شده</a>
                            {% else %}
                                <a href="#" class="btn btn-info disabled">درخواست فرستاده شده</a>

                            {% endif %}

                        {% endif %}
                    {% endif %}
                    
                {% else %}
                    <a href="{% url 'user:login' %}" class="btn btn-info">وارد شوید</a>
                {% endif %}
            </div>
        </div>
    </section>
    {% include "article/users_request.html" %}
</section>
{% endblock content %}

templates/article/article_create_update.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block title %}ایجاد درخواست{% endblock title %}
{% block content %}
<section class="cards d-flex flex-column align-items-center">

    <section class="custom-card rounded">
        <div>
            <div class="card-header form-header d-flex flex-column flex-sm-row align-items-center justify-content-between row border-bottom border-secondary">
                <div class="card-header-right d-flex align-items-center">
                    <h5>نوشتن درخواست جدید</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">

                </div>
            </div>
            <form class="create-update-form" method="POST">
                {% csrf_token %}
                <div class="card-custom-body">
                    {% if user.is_superuser %}
                        <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.author|as_crispy_field}}
                        </div>
                        <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.apply|as_crispy_field}}
                        </div>
                        <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.accepted|as_crispy_field}}
                            {{form.rejected|as_crispy_field}}
                        </div>
                    {% endif %}

                    <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                        {{form.server|as_crispy_field}}
                        {{form.min_rank|as_crispy_field}}

                    </div>

                    <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                        {{form.role|as_crispy_field}}
                    </div>
                    <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                            {{form.min_level|as_crispy_field}}
                            {{form.min_kd|as_crispy_field}}
                            {{form.min_time_to_play|as_crispy_field}}
                            {% if user.is_superuser %}
                                {{form.publish|as_crispy_field}}    
                            {% endif %}
                    </div>
                </div>
                <div class="row d-flex justify-content-around">
                    {% if request.resolver_match.url_name == "edit" %}
                        <button type="submit" class="col-12 col-md-4 btn btn-success">آپدیت درخواست</button>
                        <a href="{% url 'article:delete' request.resolver_match.kwargs.pk %}" class="col-12 col-md-4 mt-2 mt-md-0 btn btn-danger">حذف درخواست</a>
                    {% else %}
                        <button type="submit" class="col-6 btn btn-success">ثبت درخواست</button>
                    {% endif %}
                </div>
            </form>
        </div>
    </section>
    

</section>
{% endblock content %}

templates/article/article_delete.html
{% extends 'article/base.html' %}
{% load crispy_forms_tags %}



{% block title %}حذف درخواست{% endblock title %}
{% block content %}
<section class="cards d-flex flex-column align-items-center">

    <section class="custom-card rounded">
        <div>
            <div class="card-header form-header d-flex flex-column flex-sm-row align-items-center justify-content-between row border-bottom border-secondary">
                <div class="card-header-right d-flex align-items-center">
                    <h5>حذف پست</h5>
                </div>
                <div class="card-header-left flex-column flex-lg-row">

                </div>
            </div>
            <form class="delete-article-form" method="POST">
                {% csrf_token %}
                <div class="card-custom-body">
                    <div class="row form-group flex-column flex-lg-row justify-content-around align-items-center">
                            <p>از حذف این پست اطمینان دارید؟</p>
                    </div>


                </div>
                <div class="row d-flex justify-content-center">
                    <button type="submit" class="col-6 btn btn-danger">حذف پست</button>
                </div>
            </form>
        </div>
    </section>
    

</section>
{% endblock content %}

templates/article/aside.html
{% load base_tags %}
<aside>
    <section class="last-news">
        <div class="aside-header border-bottom m-2">
            <span class="p-1 h5">اطلاعیه ها</span><span class="badge badge-danger">جدید</span>
        </div>
        <div class="aside-body mx-2 mt-1">
            <p class="bg-white-color rounded p-1">سایت به زودی بروزرسانی میشود</p>
            <p class="bg-white-color rounded p-1">افزایش تعداد درخواست در هفته</p>
        </div>

    </section>
    <section class="news-letter mb-3">
        <div class="aside-header border-bottom m-2">
            <span class="p-1 h5">خبرنامه</span>
        </div>
        <div class="aside-body d-flex justify-content-center">
            {% newsletter request %}
        </div>
    </section>
</aside>

templates/article/footer.html
<section class="footer d-flex justify-content-center align-items-center">
    <div>
        <h5 class="">طراحی شده توسط علی ضابط پور</h5>
    </div>
</section>

templates/article/home.html
{% extends 'article/base.html' %}
{% load base_tags %}

{% block title %}خانه{% endblock title %}

{% block content %}
    {% articles articles request %}
{% endblock %}
{% block pagination %}
    {% pagination articles 'article:home' page_range %}
    
{% endblock %}

templates/article/navbar.html
{% load static %}
<nav class="header d-flex justify-content-sm-around px-2 px-sm-0 justify-content-between align-items-center bg-gray-color text-white">
    <section id="menu-toggle" class="mobile-menu d-sm-none d-block">
        <span class="border-secondary px-1 border rounded "><i class="fas fa-ellipsis-h pointer"></i></span>
    </section>
    <section class="right-header">
        <img class="logo" src="{% static 'article/assets/images/logo.png' %}" alt="">
        <ul class="menu d-none d-sm-flex">
            <li><i class="fas fa-home"></i><a href="{% url 'article:home' %}">خانه</a></li>
            <li><i class="fas fa-users"></i><a href="{% url 'article:teams' %}">تیم ها</a></li>
            {% if user.is_authenticated %}
                <li><i class="fas fa-user"></i><a href="{% url 'user:articles' %}">درخواست های شما</a></li>
                <li><i class="fas fa-user"></i><a href="{% url 'article:create' %}">نوشتن درخواست جدید</a></li>
            {% endif %}
        </ul>
    </section>
    <section class="left-header">
        {% if user.is_authenticated %}
            <a href="{% url 'user:user_setting' %}" class="btn btn-info"><i class="fas fa-user mx-1"></i>پروفایل</a>
        {% else %}
            <span class="login-button">
                <a href="{% url 'user:login' %}" class="btn btn-light">ورود</a>
            </span>
            <span>/</span>
            <span class="signup-button">
                <a href="{% url 'user:signup' %}" class="btn btn-light">ثبت نام</a>
            </span>
        {% endif %}
    </section>
</nav>

templates/article/notif.html
<section class="main-notification d-flex justify-content-center">
    <div class="bg-danger rounded notification-container d-flex align-items-center">
        <i id="close-notif" class="fas fa-window-close text-dark pointer"></i>
        <span class="text-white mr-4">متن نوتیف ما که یخورده زیاد شده</span>
    </div>
</section>

templates/article/users_request.html
<div class="container animated animated-done bootdey mt-2" data-animate="fadeIn" data-animate-delay="0.05" style="animation-delay: 0.05s;">
    <hr class="hr-lg mt-0 mb-2 w-10 mx-auto hr-primary">
    <h2 class="text-slab text-center alert alert-info text-uppercase mt-0 mb-5">
        درخواست های <span class="font-weight-bold">تیم</span>
    </h2>
    <div class="timeline timeline-left mx-lg-10">
            <div class="timeline-breaker bg-info">درخواست های فرستاده شده</div>
            <!--Timeline item 1-->
            {% if article.new_apply != 0 %}

                {% for user in article.apply.all %}
                    

                    {% if user not in article.accepted.all and user not in article.rejected.all %}
                    <div class="timeline-item mt-3 row text-center p-2">
                        <div class="col-12 font-weight-bold text-md-center">نام کاربری:<a class="text-primary" href="{% url 'user:account_profile' user.username %}">{{user.username}}</a></div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">سرور:{{user.acc_detail.get_server_display}}</div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">کی دی:{{user.acc_detail.kd}}</div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">رنک:{{user.acc_detail.rank}}</div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">لول:{{user.acc_detail.level}}</div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">سیزن شروع:{{user.acc_detail.start_season}}</div>
                        <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">تایم بازی:{{user.acc_detail.time_to_play}} ساعت</div>
                        <div class="col-12 font-weight-bold my-role text-md-center p-1">نقش:{{user.acc_detail.role}}</div>
                        {% if request.user == article.author %}
                            <a href="{% url 'article:accept' article.id user.username %}" class="btn btn-success col-12 col-md-6 mb-2 mb-md-0">قبول کردن</a>
                            <a href="{% url 'article:reject' article.id user.username %}" class="btn btn-danger col-12 col-md-6">رد کردن</a>
                        {% endif %}

                    </div>
                    {% endif %}

                {% empty %}
                    <div class="timeline-item mt-3 row text-center p-2">

                        <p class="alert alert-info text-center col-12 mb-2 mb-md-0">درخواستی وجود ندارد</p>
                    </div>
                {% endfor %}
            {% else %}
                <div class="timeline-item mt-3 row text-center p-2">

                        <p class="alert alert-info text-center col-12 mb-2 mb-md-0">درخواستی فعالی وجود ندارد</p>
                </div>
            {% endif %}
            <div class="timeline-breaker bg-success timeline-breaker-middle">درخواست های قبول شده</div>
            {% for user in article.accepted.all %}
                <div class="timeline-item mt-3 row text-center p-2">
                    <div class="col-12 font-weight-bold text-md-center">نام کاربری:<a class="text-primary" href="{% url 'user:account_profile' user.username %}">{{user.username}}</a></div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">سرور:{{user.acc_detail.server}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">کی دی:{{user.acc_detail.kd}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">رنک:{{user.acc_detail.rank}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">لول:{{user.acc_detail.level}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">سیزن شروع:{{user.acc_detail.start_season}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">تایم بازی:{{user.acc_detail.time_to_play}} ساعت</div>
                    <div class="col-12 font-weight-bold my-role text-md-center">نقش:{{user.acc_detail.role}}</div>
                    {% if request.user == article.author %}
                        <div class="col-12 font-weight-bold alert alert-success text-md-center">ایدی عددی {{user.username}} در بازی:{{user.acc_detail.id_game}}</div>
                        <div class="col-12 font-weight-bold alert alert-success text-md-center">یوزرنیم {{user.username}} در بازی:{{user.acc_detail.username_game}}</div>
                    {% elif request.user == user  %}
                        <div class="col-12 font-weight-bold alert alert-success text-md-center">ایدی عددی {{article.author.username}} در بازی:{{article.author.acc_detail.id_game}}</div>
                        <div class="col-12 font-weight-bold alert alert-success text-md-center">یوزرنیم {{article.author.username}} در بازی:{{article.author.acc_detail.username_game}}</div>
                    {% else %}
                        <p class="alert alert-success text-center col-12 mb-2 mb-md-0">قبول شده</p>
                    {% endif %}
                </div>
            {% empty %}
                <div class="timeline-item mt-3 row text-center p-2">

                    <p class="alert alert-info text-center col-12 mb-2 mb-md-0">کسی قبول نشده است</p>
                </div>
            {% endfor %}


            <div class="timeline-breaker bg-danger timeline-breaker-middle">درخواست های رد شده</div>
            {% for user in article.rejected.all %}
                <div class="timeline-item mt-3 row text-center p-2">
                    <div class="col-12 font-weight-bold text-md-center">نام کاربری:<a class="text-primary" href="{% url 'user:account_profile' user.username %}">{{user.username}}</a></div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">سرور:{{user.acc_detail.server}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">کی دی:{{user.acc_detail.kd}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">رنک:{{user.acc_detail.rank}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center">لول:{{user.acc_detail.level}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">سیزن شروع:{{user.acc_detail.start_season}}</div>
                    <div class="col-12 col-sm-6 font-weight-bold text-md-center p-1">تایم بازی:{{user.acc_detail.time_to_play}} ساعت</div>
                    <div class="col-12 font-weight-bold my-role text-md-center">نقش:{{user.acc_detail.role}}</div>
                    <p class="alert alert-danger text-center col-12 mb-2 mb-md-0">رد شده</p>

                </div>
            {% empty %}
                <div class="timeline-item mt-3 row text-center p-2">

                    <p class="alert alert-info text-center col-12 mb-2 mb-md-0">کسی رد نشده است</p>
                </div>
            {% endfor %}



    </div>
</div>